galaxy_info:
  author: Luciano Sampaio
  description: Provisions an Ubuntu Desktop 24.04 machine with development packages, pipx tools, and Ansible Galaxy collections.
  company: thecodemaster.net

  license: MIT

  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags:
    - proxmox
    - ubuntu
    - terraform

dependencies:
  - role: common
