---
- name: Updating apt repository and cache
  apt:
    update_cache: yes

- name: Upgrading full distro packages
  apt:
    upgrade: "dist"

- name: Adding Google Chrome signing key so it can be installed by apt-get
  import_tasks: "roles/common/tasks/packages/google-chrome.yml"

- name: Installing apt packages
  import_tasks: "roles/common/tasks/packages/apt.yml"
  vars:
    packages:
      - { name: "sudo" } # To enable elevated command.
      - { name: "openssh-server" } # To enable SSH.
      - { name: "qemu-guest-agent" } # To enhance Proxmox integration with the VM.
      - { name: "ethtool" } # To enable Wake-on-Lan.
      - { name: "xrdp" } # To enable Microsoft Remote Connection.
      - { name: "ansible" }
      - { name: "ansible-lint" }
      - { name: "git" }
      - { name: "pip" }
      - { name: "google-chrome-stable" }

- name: Setting up the XRDP package
  import_tasks: "roles/common/tasks/packages/xrdp.yml"

- name: Setting up the Git package
  import_tasks: "roles/common/tasks/packages/git.yml"
  vars:
    config:
      - { scope: "global", name: "user.name", value: "{{ git_user_name }}" }
      - { scope: "global", name: "user.email", value: "{{ git_user_email }}" }

- name: Installing snap packages
  import_tasks: "roles/common/tasks/packages/snap.yml"
  vars:
    packages:
      - { name: "code", classic: "yes" }
      - { name: "postman" }
      - { name: "packer" }
      # - { name: "docker" }

- name: Checking if a reboot is needed
  stat:
    path: "/var/run/reboot-required"
    get_md5: "no"
  register: "reboot_required"

- name: Rebooting the host if kernel was updated
  reboot:
    msg: "Reboot initiated by Ansible for kernel updates."
    connect_timeout: 5
    reboot_timeout: 120
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: "whoami"
  when: reboot_required.stat.exists
