---
# The git config for my user. String was encoded on base64 to avoid spammers.
git_user_name: "THVjaWFubyBTYW1wYWlv"
git_user_email: "bHNhbXBhaW93ZWJAZ21haWwuY29t"

git_path: "~/git"
datacenter_path: "{{ git_path }}/datacenter"
ansible_path: "{{ datacenter_path }}/ansible"
docker_path: "{{ datacenter_path }}/docker"
packer_path: "{{ datacenter_path }}/packer"
projects_path: "{{ datacenter_path }}/projects"
springboot_path: "{{ datacenter_path }}/spring-boot"
terraform_path: "{{ datacenter_path }}/terraform"
home_path: "{{ git_path }}/home"

# Path of the SSL CA Certificate.
certificates_authority_path: "/usr/local/share/ca-certificates"
ca_certificate_path: "{{ certificates_authority_path }}/ca.lan.homelab.crt"

# For Google Chrome to trust our Certificate Authority.
# "C,," -> root.
# ",,"  -> intermediate.
nssdb_path: "$HOME/.pki/nssdb"
nssdb_certificates:
  - {trust: "C,,", name: "HomeLab-Certificate-Authority", path: "{{ ca_certificate_path }}"}
