---
# The git config for my user. String was encoded on base64 to avoid spammers.
git_user_name: "THVjaWFubyBTYW1wYWlv"
git_user_email: "bHNhbXBhaW93ZWJAZ21haWwuY29t"

git_path: "~/git"
datacenter_path: "{{ git_path }}/datacenter"
ansible_path: "{{ datacenter_path }}/01-ansible"
packer_path: "{{ datacenter_path }}/02-packer"
terraform_path: "{{ datacenter_path }}/03-terraform"
docker_path: "{{ datacenter_path }}/04-docker"
springboot_path: "{{ datacenter_path }}/05-spring-boot"
projects_path: "{{ datacenter_path }}/06-projects"
home_path: "{{ git_path }}/home"

# Path of the SSL CA Certificate.
certificates_authority_path: "/usr/local/share/ca-certificates"
ca_certificate_path: "{{ certificates_authority_path }}/ca.lan.homelab.crt"

# For Google Chrome to trust our Certificate Authority.
# "C,," -> root.
# ",,"  -> intermediate.
nssdb_path: "$HOME/.pki/nssdb"
nssdb_certificates:
  - {trust: "C,,", name: "HomeLab-Certificate-Authority", path: "{{ ca_certificate_path }}"}
