---
# The name of the root user used in VM.
ansible_user: "lsampaio"

# The id of the password saved in the secret manager.
root_password_id: "{{ ansible_user }}"

# The password of the root user used in VM.
ansible_password: "{{ lookup('pipe', 'secret-tool lookup password ' + root_password_id) }}"

# The git config for my user. String was encoded on base64 to avoid spammers.
git_user_name: "THVjaWFubyBTYW1wYWlv"
git_user_email: "bHNhbXBhaW93ZWJAZ21haWwuY29t"

git_path: "~/git"
datacenter_path: "{{ git_path }}/datacenter"
ansible_path: "{{ datacenter_path }}/ansible"
packer_path: "{{ datacenter_path }}/packer"
projects_path: "{{ datacenter_path }}/projects"
terraform_path: "{{ datacenter_path }}/terraform"
