---
# The name of the root user used in VM.
ansible_user: "administrator"

# The id of the password saved in the secret manager.
root_password_id: "{{ password_id }}"

# The password of the root user used in VM.
ansible_password: "{{ lookup('pipe', 'secret-tool lookup password ' + root_password_id) }}"

# The sudo password.
ansible_become_password: "{{ ansible_password }}"

# The git config for my user. String was encoded on base64 to avoid spammers.
git_user_name: "THVjaWFubyBTYW1wYWlv"
git_user_email: "bHNhbXBhaW93ZWJAZ21haWwuY29t"

git_path: "~/git"
datacenter_path: "{{ git_path }}/datacenter"
ansible_path: "{{ datacenter_path }}/ansible"
packer_path: "{{ datacenter_path }}/packer"
projects_path: "{{ datacenter_path }}/projects"
terraform_path: "{{ datacenter_path }}/terraform"
springboot_path: "{{ datacenter_path }}/spring-boot"
home_path: "{{ git_path }}/home"

# Path of the SSL CA Certificate.
certificates_authority_path: "/usr/local/share/ca-certificates"
ca_certificate_path: "{{ certificates_authority_path }}/certificate-authority.lan.homelab.crt"

# For Google Chrome to trust our Certificate Authority.
# "C,," -> root.
# ",,"  -> intermediate.
nssdb_path: "$HOME/.pki/nssdb"
nssdb_certificates:
  - {trust: "C,,", name: "HomeLab-Certificate-Authority", path: "{{ ca_certificate_path }}"}
