---
- name: "Creating the list of favorite applications"
  ansible.builtin.set_fact:
    favorite_applications:
      - "org.gnome.Nautilus.desktop"
      - "google-chrome.desktop"
      - "code.desktop"
      - "org.gnome.Terminal.desktop"
      - "gnome-control-center.desktop"
      - "org.gnome.seahorse.Application.desktop"
      - "gnome-system-monitor.desktop"

- name: "Adding the favorite applications in the Dock"
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "{{ favorite_applications }}"
    state: "present"
