---
- name: "Ensure all the git directories exists"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    mode: "0755"
  loop:
    - {path: "{{ git_path }}"}
    - {path: "{{ datacenter_path }}"}
    - {path: "{{ ansible_path }}"}
    - {path: "{{ docker_path }}"}
    - {path: "{{ packer_path }}"}
    - {path: "{{ projects_path }}"}
    - {path: "{{ springboot_path }}"}
    - {path: "{{ terraform_path }}"}
    - {path: "{{ home_path }}"}

- name: "Cloning my git repositories"
  ansible.builtin.git:
    repo: "https://github.com/lsampaioweb/{{ item.repo }}.git"
    dest: "{{ item.dest }}"
    clone: true
    update: true
  register: "output"
  failed_when: (output.msg is defined) and 'Local modifications exist' not in output.msg
  loop:
    - {repo: "homelab-datacenter", dest: "{{ git_path }}/homelab-datacenter"}
    - {repo: "git-template-repository", dest: "{{ git_path }}/git-template-repository"}
    # Ansible
    - {repo: "ansible-common-tasks", dest: "{{ ansible_path }}/ansible-common-tasks"}
    - {repo: "ansible-kvm-cloud-init", dest: "{{ ansible_path }}/ansible-kvm-cloud-init"}
    # Docker
    - {repo: "gitea-docker", dest: "{{ docker_path }}/gitea"}
    - {repo: "jenkins-docker", dest: "{{ docker_path }}/jenkins"}
    - {repo: "jenkins-shared-pipeline-libraries", dest: "{{ docker_path }}/jenkins-shared-pipeline-libraries"}
    - {repo: "nexus-docker", dest: "{{ docker_path }}/nexus"}
    - {repo: "openldap-docker", dest: "{{ docker_path }}/openldap"}
    - {repo: "portainer-docker", dest: "{{ docker_path }}/portainer"}
    - {repo: "sonarqube-docker", dest: "{{ docker_path }}/sonarqube"}
    - {repo: "traefik-docker", dest: "{{ docker_path }}/traefik"}
    - {repo: "vault-docker", dest: "{{ docker_path }}/vault"}
    # Packer
    - {repo: "packer-proxmox-ubuntu-22-04-clone", dest: "{{ packer_path }}/packer-proxmox-ubuntu-22-04-clone"}
    - {repo: "packer-proxmox-ubuntu-22-04-iso", dest: "{{ packer_path }}/packer-proxmox-ubuntu-22-04-iso"}
    - {repo: "proxmox-ubuntu-22-04-desktop-raw", dest: "{{ packer_path }}/proxmox-ubuntu-22-04-desktop-raw"}
    - {repo: "proxmox-ubuntu-22-04-desktop-standard", dest: "{{ packer_path }}/proxmox-ubuntu-22-04-desktop-standard"}
    - {repo: "proxmox-ubuntu-22-04-server-raw", dest: "{{ packer_path }}/proxmox-ubuntu-22-04-server-raw"}
    - {repo: "proxmox-ubuntu-22-04-server-standard", dest: "{{ packer_path }}/proxmox-ubuntu-22-04-server-standard"}
    - {repo: "proxmox-ubuntu-22-04-server-std-docker", dest: "{{ packer_path }}/proxmox-ubuntu-22-04-server-std-docker"}
    # Projects
    - {repo: "dhcp", dest: "{{ projects_path }}/dhcp"}
    - {repo: "dns", dest: "{{ projects_path }}/dns"}
    - {repo: "jump-server", dest: "{{ projects_path }}/jump-server"}
    - {repo: "load-balancer", dest: "{{ projects_path }}/load-balancer"}
    - {repo: "ntp", dest: "{{ projects_path }}/ntp"}
    - {repo: "openssl-certificates", dest: "{{ projects_path }}/openssl-certificates"}
    - {repo: "proxmox-cluster", dest: "{{ projects_path }}/proxmox-cluster"}
    - {repo: "T1600G-28TS-SG2424", dest: "{{ projects_path }}/T1600G-28TS-SG2424"}
    - {repo: "tplink_router_ax1800", dest: "{{ projects_path }}/tplink_router_ax1800"}
    # Spring Boot
    - {repo: "spring-boot-tutorial", dest: "{{ springboot_path }}/spring-boot-tutorial"}
    # Terraform
    - {repo: "terraform-local-dynamic-inventory", dest: "{{ terraform_path }}/terraform-local-dynamic-inventory"}
    - {repo: "terraform-proxmox-homelab-project", dest: "{{ terraform_path }}/terraform-proxmox-homelab-project"}
    - {repo: "terraform-proxmox-vm-qemu", dest: "{{ terraform_path }}/terraform-proxmox-vm-qemu"}
    - {repo: "terraform-random-target-node", dest: "{{ terraform_path }}/terraform-random-target-node"}
    # Home
    - {repo: "backup-restic-s3-minio", dest: "{{ home_path }}/backup-restic-s3-minio"}
    - {repo: "home-edge-esxi", dest: "{{ home_path }}/home-edge-esxi"}
    - {repo: "home-edge-firewall", dest: "{{ home_path }}/home-edge-firewall"}
    - {repo: "home-edge-grafana", dest: "{{ home_path }}/home-edge-grafana"}
    - {repo: "home-edge-k3s", dest: "{{ home_path }}/home-edge-k3s"}
    - {repo: "home-edge-ldap", dest: "{{ home_path }}/home-edge-ldap"}
    - {repo: "home-edge-minio", dest: "{{ home_path }}/home-edge-minio"}
    - {repo: "home-edge-postgresql", dest: "{{ home_path }}/home-edge-postgresql"}
    - {repo: "home-edge-zabbix", dest: "{{ home_path }}/home-edge-zabbix"}

- name: "Copying homelab VSCode workspace file to the target host"
  ansible.builtin.copy:
    src: "Homelab.code-workspace"
    dest: "{{ git_path }}/"
    mode: "664"
