---
- name: "Setting up Git"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/git-config.yml"
  vars:
    config:
      - {scope: "global", name: "user.name", value: "{{ git_user_name | b64decode }}"}
      - {scope: "global", name: "user.email", value: "{{ git_user_email | b64decode }}"}
      - {scope: "global", name: "pull.rebase", value: "false"}
      - {scope: "global", name: "init.defaultBranch", value: "main"}

- name: "Managing vscode extentions"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/vscode-extention.yml"
  vars:
    extentions:
      - {name: "redhat.ansible"}
      - {name: "redhat.vscode-yaml"}
      - {name: "redhat.vscode-xml"}
      - {name: "vscode-icons-team.vscode-icons"}
      - {name: "ms-vscode-remote.remote-ssh"}
      - {name: "4ops.packer"}
      - {name: "hashicorp.hcl"}
      - {name: "HashiCorp.terraform"}
      - {name: "wholroyd.jinja"}
      - {name: "tomoki1207.pdf"}
      - {name: "eamodio.gitlens"}
      - {name: "humao.rest-client"}
      - {name: "dbaeumer.vscode-eslint"}
      - {name: "vscjava.vscode-java-pack"}
      - {name: "vscjava.vscode-spring-initializr"}
      - {name: "vscjava.vscode-spring-boot-dashboard"}
      - {name: "vmware.vscode-spring-boot"}

- name: "Setting up XClip"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/xclip.yml"

# - name: "Adding our self signed certificate authority to the Google Chrome trust database"
#   become: false
#   ansible.builtin.import_tasks: "roles/common/tasks/debian/os/nssdb.yml"
#   when: nssdb_path is defined

- name: "Adding our self signed certificate authority to the Google Chrome trust database"
  when: nssdb_path is defined
  ansible.builtin.include_role:
    name: "common"
    tasks_from: "debian/os/nssdb.yml"
    apply:
      become: false
