---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - {name: "sudo"} # To enable elevated command.
      - {name: "openssh-server"} # To enable SSH.
      - {name: "qemu-guest-agent"} # To enhance Proxmox integration with the VM.
      - {name: "ethtool"} # To enable Wake-on-Lan.
      - {name: "xrdp"} # To enable Microsoft Remote Connection.
      - {name: "traceroute"} # It helps debug network problems.
      - {name: "nikto"} # To run vulnerabilidade scans.
      - {name: "chrome-gnome-shell"} # To enable Microsoft Remote Connection multiple logins.
      - {name: "whois"} # To enable mkpasswd command.
      - {name: "xclip"} # Copy to clipboard.
      - {name: "python-is-python3"}
      - {name: "pip"}
      - {name: "git"}
      - {name: "sshpass"}
      - {name: "libsecret-tools"}
      - {name: "net-tools"}
      - {name: "curl"}
      - {name: "tree"}
      - {name: "gnome-keyring"}
      - {name: "dbus-x11"} # Required for the community.general.dconf module.

- name: "Installing pip packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/pip.yml"
  vars:
    packages:
      - {name: "ansible"}
      - {name: "ansible-lint"}
      - {name: "psutil"} # Required for the community.general.dconf module.
      - {name: "passlib"} # Required to use bcrypt.

- name: "Setting up the XRDP package"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/xrdp.yml"

- name: "Setting up the Google packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/google-chrome.yml"

- name: "Setting up VSCode application"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/vscode.yml"

- name: "Setting up the HashiCorp packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/hashicorp.yml"

- name: "Setting up the Git package"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/git.yml"
  vars:
    config:
      - {scope: "global", name: "user.name", value: "{{ git_user_name | b64decode }}"}
      - {scope: "global", name: "user.email", value: "{{ git_user_email | b64decode }}"}
      - {scope: "global", name: "pull.rebase", value: "false"}
      - {scope: "global", name: "init.defaultBranch", value: "main"}

- name: "Installing all the required collections"
  community.general.ansible_galaxy_install:
    type: "collection"
    name: "{{ item }}"
  loop:
    - "community.general" # To work with dconf.
