---
- name: "Installing snap packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/snap.yml"
  vars:
    packages:
      - {name: "code", classic: "yes"}
      - {name: "postman"}

- name: "Setting up VSCode application"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/vscode.yml"

- name: "Setting up the HashiCorp packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/hashicorp.yml"

- name: "Setting up the Git package"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/git.yml"
  vars:
    config:
      - {scope: "global", name: "user.name", value: "{{ git_user_name | b64decode }}"}
      - {scope: "global", name: "user.email", value: "{{ git_user_email | b64decode }}"}
      - {scope: "global", name: "pull.rebase", value: "false"}
      - {scope: "global", name: "init.defaultBranch", value: "main"}
