---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "installing-packages.yml"

- name: "Copying the unlock-keyring function"
  ansible.builtin.import_tasks: "unlock-keyring.yml"

- name: "Adding the favorite applications in the Dock"
  ansible.builtin.import_tasks: "adding-favorite-apps-to-dock.yml"

- name: "Setting the dark theme"
  ansible.builtin.import_tasks: "dark-theme.yml"

- name: "Cloning the default git repositories"
  become: false
  ansible.builtin.import_tasks: "clone-git-repositories.yml"

- name: "Removing unnecessary packages"
  ansible.builtin.import_tasks: "removing-packages.yml"

- name: "Checking if a reboot is required"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/reboot-if-required.yml"
