---
- name: Restart xrdp
  systemd:
    name: "xrdp"
    state: "restarted"

- name: Reconfiguring Timezone
  command: "dpkg-reconfigure --frontend noninteractive tzdata"

- name: Restarting Systemd-Timesyncd
  service:
    name: "systemd-timesyncd"
    state: "restarted"

- name: Generating Grub File
  command: "update-grub"
