---
- name: "Personal Development Environment Setup"
  tags:
    - "personal_config"
  block:
    - name: "Setting up the disks"
      when: vgs is defined
      ansible.builtin.import_role:
        name: "common"
        tasks_from: "debian/os/local-storage"

    - name: "Installing personal development packages"
      ansible.builtin.import_tasks: "packages"
