---
- name: "Signing the Host OpenSSH keypair with the CA key"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/sign-ssh-keypair.yml"

# - name: "Setting up the disks"
#   ansible.builtin.import_tasks: "local-storage.yml"

- name: "Installing required packages"
  ansible.builtin.import_tasks: "installing-packages.yml"

- name: "Removing unnecessary packages"
  ansible.builtin.import_tasks: "removing-packages.yml"

- name: "Checking if a reboot is required"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/reboot-if-required.yml"
