---
- name: "Including OS-specific or default variables for global packages"
  ansible.builtin.include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution_release'] }}.yml"
        - "packages.yml"
      paths:
        - "{{ role_path }}/vars"

- name: "Installing global APT packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    upgrade: "full"
    packages: "{{ apt_packages }}"
    autoclean: true
    autoremove: true

- name: "Installing global PIPX packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/pipx"
  vars:
    packages: "{{ pipx_packages }}"

- name: "Installing Ansible Galaxy collections"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/ansible-galaxy"
  vars:
    packages: "{{ ansible_galaxy_collections }}"

- name: "Installing VS Code"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/vscode"
