---
- name: "Including OS-specific or default variables for global packages"
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_lsb.codename }}.yml"
    - "packages.yml"

- name: "Installing global APT packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    upgrade: true
    packages: "{{ apt_packages }}"
    autoclean: true
    autoremove: true

- name: "Installing global PIPX packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/pipx"
  vars:
    packages: "{{ pipx_packages }}"

- name: "Installing Ansible Galaxy collections"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/ansible-galaxy"
  vars:
    packages: "{{ ansible_galaxy_collections }}"
