---
- name: "Ensuring UFW package is installed"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/os/ufw-install"

- name: "Ensuring IPv6 is disabled in UFW's default configuration"
  ansible.builtin.lineinfile:
    path: "/etc/default/ufw"
    regexp: "^IPV6="
    line: "IPV6=no"
    state: "present"

- name: "Applying UFW rules"
  ansible.builtin.include_role:
    name: "common"
    tasks_from: "debian/os/ufw-configure-rule"
  loop: "{{ ufw.rules | default([]) }}"
  loop_control:
    label: "{{ item.rule | default('') }} {{ item.name | default('') }}"
