---
- name: "Adding UFW rules"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/ufw.yml"
  vars:
    rules:
      - {
        rule: "allow",
        proto: "tcp",
        to_port: "8100:8200",
        src: "192.168.100.0/28",
        comment: "Cloud-Init: Allow access to user-data ports (8100-8200) from Packer VLAN only"
      }
