---
- name: "Setting up DNS"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/dns.yml"

- name: "Changing the hostname"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/hostname.yml"

- name: "Setting up Brazilian timezone"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/timezone.yml"

- name: "Setting up NTP Servers"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/ntp-servers.yml"

- name: "Disabling IPV6 on the server"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/network/ipv6-disable.yml"
