---
- name: "Changing the hostname"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/hostname.yml"

- name: "Disabling IPV6 on the server"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/network/ipv6-disable.yml"

- name: "Setting up Brazilian timezone"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/timezone.yml"

- name: "Setting up Brazilian NTP Servers"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/ntp-servers.yml"

- name: "Creating the Ansible user account"
  ansible.builtin.import_tasks: "users.yml"
