---
- name: Upgrading full distro packages
  ansible.builtin.apt:
    upgrade: "dist"

- name: Installing required packages
  import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    packages:
      - {name: "sudo"} # To enable elevated command.
      - {name: "openssh-server"} # To enable SSH.
      - {name: "qemu-guest-agent"} # To enhance Proxmox integration with the VM.
      - {name: "ethtool"} # To enable Wake-on-Lan.
      - {name: "xrdp"} # To enable Microsoft Remote Connection.
      - {name: "traceroute"} # It helps debug network problems.
      - {name: "nikto"} # To run vulnerabilidade scans.
      - {name: "chrome-gnome-shell"} # To enable Microsoft Remote Connection multiple logins.
      - {name: "whois"} # To enable mkpasswd command.
      - {name: "pip"}
      - {name: "git"}
      - {name: "sshpass"}
      - {name: "libsecret-tools"}
      - {name: "net-tools"}
      - {name: "curl"}
      - {name: "tree"}

- name: Installing pip packages
  import_tasks: "roles/common/tasks/debian/packages/pip.yml"
  vars:
    packages:
      - {name: "ansible"}
      - {name: "ansible-lint"}
      - {name: "psutil"} # Required for the community.general.dconf module.

- name: Installing snap packages
  import_tasks: "roles/common/tasks/debian/packages/snap.yml"
  vars:
    packages:
      - {name: "code", classic: "yes"}
      - {name: "postman"}

- name: Setting up the XRDP package
  import_tasks: "roles/common/tasks/debian/packages/xrdp.yml"

- name: Setting up the Google packages
  import_tasks: "roles/common/tasks/debian/packages/google-chrome.yml"

- name: Setting up VSCode application
  import_tasks: "roles/common/tasks/debian/packages/vscode.yml"

- name: Setting up the HashiCorp packages
  import_tasks: "roles/common/tasks/debian/packages/hashicorp.yml"

- name: Setting up the Git package
  import_tasks: "roles/common/tasks/debian/packages/git.yml"
  vars:
    config:
      - {scope: "global", name: "user.name", value: "{{ git_user_name | b64decode }}"}
      - {scope: "global", name: "user.email", value: "{{ git_user_email | b64decode }}"}
      - {scope: "global", name: "pull.rebase", value: "false"}
      - {scope: "global", name: "init.defaultBranch", value: "main"}
