---
- name: "Preparing the machine with the initial settings"
  ansible.builtin.import_playbook: "provision.yml"

- name: "Updating the machine"
  ansible.builtin.import_playbook: "update.yml"

- name: "Create a user account"
  ansible.builtin.import_playbook: "create_user.yml"

- name: "Preparing the machine with my user's settings"
  ansible.builtin.import_playbook: "setup_user.yml"
