---
- name: Installing and upgrading the pip package
  pip:
    name: "pip"
    state: "latest"

- name: Python packages  
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ packages }}"
