---
- name: Snap packages
  become: yes
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(omit) }}"
    channel: "{{ item.channel | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ packages }}"
