---
- name: "Updating packages"
  ansible.builtin.include_role:
    name: "common"
    tasks_from: "debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "full"
    autoclean: true
    autoremove: true
    reboot_allowed: true
