---
- name: "Updating all system packages to the latest version"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    upgrade: "full"
    autoclean: true
    autoremove: true
    reboot_allowed: true
