---
apt_packages:
  # Personal Development Tools - Unique packages not in desktop-standard foundation.
  - {name: "jq"} # Command-line JSON processor for data manipulation.
  - {name: "default-jdk"} # Java Development Kit for Java programming.

pipx_packages:
  # Personal Development Environment - Ansible tools for infrastructure management.
  - {name: "ansible", install_deps: true, global: true}
  - {name: "ansible-lint", global: true}
  - {name: "ansible", state: "inject", inject_packages: ['jmespath', 'hvac', 'certifi', 'passlib'], include_injected: true, global: true}
