---
# If the VM was on VirtualBox, comment all these lines.
# vgs:
#   - name: "ubuntu_vg"
#     disks:
#       - "/dev/sda3"
#       - "/dev/sdb1"
#     lvm:
#       - { name: "root_lvm", size: "12G", fstype: "ext4" }
#       - { name: "var_lvm", size: "12G", fstype: "ext4" }
#       - { name: "home_lvm", size: "+100%FREE", fstype: "ext4" }
