---
lvm:
  # - { device: "/dev/sda", volume_group: "ubuntu_vg" }
  - { device: "/dev/sdb", volume_group: "ubuntu_vg" }

logical_volume:
  - { name: "root_lvm", volume_group: "ubuntu_vg", filesystem_type: "ext4", size: "+30%" }
  - { name: "var_lvm", volume_group: "ubuntu_vg", filesystem_type: "ext4", size: "+30%" }
  - { name: "home_lvm", volume_group: "ubuntu_vg", filesystem_type: "ext4", size: "+45%" }
