---
vg_name: "ubuntu_vg"

lvm:
  - { name: "root_lvm", filesystem_type: "ext4", size: "12G" }
  - { name: "var_lvm", filesystem_type: "ext4", size: "10G" }
  - { name: "home_lvm", filesystem_type: "ext4", size: "+100%FREE" }
  # - { name: "opt_lvm", filesystem_type: "ext4", size: "+45%VG" }
