---
lvm:
  - {
    devices: "/dev/sdb",
    volume_group: "ubuntu_vg",
    logical_volume: [
      { name: "root_lvm", filesystem_type: "ext4", size: "+5G" },
      { name: "var_lvm", filesystem_type: "ext4", size: "+5G" },
      { name: "home_lvm", filesystem_type: "ext4", size: "+5G" }
    ]
  }
