---
vgs:
  - name: "ubuntu_vg"
    disks:
      - "/dev/sda3"
      - "/dev/sdb1"
    lvm:
      - { name: "root_lvm", size: "12G", filesystem_type: "ext4" }
      - { name: "var_lvm", size: "10G", filesystem_type: "ext4" }
      - { name: "home_lvm", size: "+100%FREE", filesystem_type: "ext4" }
