galaxy_info:
  author: Luciano Sampaio
  description: Updates all system packages on an Ubuntu Desktop workstation to the latest version.

  license: MIT

  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags:
    - proxmox
    - ubuntu
    - ansible
    - desktop

dependencies:
  - role: common
